version: '3'
services:
  php:
    build: build/php
    expose:
      - '9000'
    depends_on:
      - mongodb
      - mysqldb
    volumes:
      - ./app:/var/www/html/symfony:cached
      - ./logs:/var/log
      - /var/www/symfony/vendor
  web:
    build: build/nginx
    restart: always
    ports:
        - '80:80'
    depends_on:
        - php
    volumes:
        - ./app:/var/www/html/symfony:cached
  
  mysqldb:
    image: mariadb
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: fabop_directory
        MYSQL_USER: app_access
        MYSQL_PASSWORD: 3zzHK7bVrchfZrRy33a9P2VpVq2QnzwGjcAYFNtDQFcYZ3nyFpwDFCWEELaXfEug
  mongodb:
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: app_access
        MONGO_INITDB_ROOT_PASSWORD: 3zzHK7bVrchfZrRy33a9P2VpVq2QnzwGjcAYFNtDQFcYZ3nyFpwDFCWEELaXfEug
        MONGO_INITDB_DATABASE: admin
    build: build/mongodb