swiftmailer:
    transport:  '%env(MAIL_TRANSPORT_TYPE)%'
    encryption: '%env(MAIL_ENCRYPTION)%'
    auth_mode:  '%env(MAIL_AUTHMODE)%'
    host:       '%env(MAIL_HOST)%'
    username:   '%env(MAIL_USERNAME)%'
    password:   '%env(MAIL_PASSWORD)%'
    spool: { type: 'memory' }
